Feature 50 network sort working
nology-tech/jersey-client-project pull request #36
Opened 2021-11-01 16:54 UTC by iKarans

2021-11-02 14:28 UTC, AdamDCosta commented on src/components/AlertFilter/AlertFilter.scss
> +    color: #aab3be;
Use a variable here

2021-11-02 14:28 UTC, AdamDCosta commented on src/components/AlertFilter/AlertFilter.scss
> +    color: #2d3748;
should be a variable

2021-11-02 14:34 UTC, AdamDCosta commented on src/components/AlertPageButton/AlertPageButton.jsx
> +        className = "alerts-table__pages-buttons-button alert__button-active"
should be a modifier - alerts-table__pages--buttons-button, same with alert__button-active (--active)

2021-11-02 14:34 UTC, AdamDCosta commented on src/components/AlertPageButton/AlertPageButton.jsx
> +        className = "alerts-table__pages-buttons-button"
same as above

2021-11-02 14:45 UTC, AdamDCosta commented on src/containers/Alerts/Alerts.jsx
> +                    : "alerts-table__alert-arrow-inactive"
active and inactive should be modifiers

2021-11-02 14:45 UTC, AdamDCosta commented on src/containers/Alerts/Alerts.jsx
> +                    : "alerts-table__time-arrow-inactive"
as above

2021-11-02 14:45 UTC, AdamDCosta commented on src/containers/Alerts/Alerts.jsx
> +                    : "alerts-table__importance-arrow-inactive"
as above

2021-11-02 14:46 UTC, AdamDCosta commented on src/containers/Alerts/Alerts.scss
> +    }
as above

2021-11-02 14:46 UTC, AdamDCosta commented on src/containers/Alerts/Alerts.scss
> +        }
as above

2021-11-02 14:46 UTC, AdamDCosta commented on src/containers/Alerts/Alerts.scss
> +.alert__filter-inactive {
and again

2021-11-03 14:36 UTC, Charlie-robin requested changes
We will need to try and simplify this at some point but if you could just look at the ternary.

2021-11-03 14:36 UTC, Charlie-robin commented on src/containers/Alerts/Alerts.jsx
> +          : b.alertType > a.alertType
Simplify this, just because you can doesn't mean you should. you have multiple conditions returning the same number try and just chain && the conditions together.

2021-11-03 14:36 UTC, Charlie-robin commented on src/containers/Alerts/Alerts.jsx
> +        {/* <ChatButton /> */}
Remove this

2021-11-04 15:56 UTC, Charlie-robin approved these changes

2021-11-04 15:57 UTC, merged