Feature 74 settings theme toggle
nology-tech/jersey-client-project pull request #51
Opened 2021-11-04 16:31 UTC by iagardi

2021-11-04 16:52 UTC, hoopercode approved these changes

2021-11-04 16:52 UTC, hoopercode commented on src/components/ThemeSettings/ThemeSettings.jsx
> +            <button onClick={handleApply} className="themesettings__form--radio-applybutton">Apply</button>
BEM

2021-11-05 14:11 UTC, Charlie-robin requested changes

2021-11-05 14:11 UTC, Charlie-robin commented on src/components/ThemeSettings/ThemeSettings.scss
> +.themesettings {
This should be `theme-settings`

2021-11-05 14:11 UTC, Charlie-robin commented on src/components/ThemeSettings/ThemeSettings.scss
> +@use "../../assets/styles/typography"as *;
You shouldn't need `@use "../../assets/styles/typography"as *;`

2021-11-05 14:44 UTC, merged